package cn.com.cretech.util

enum class NetWorkSign {

    NET_CONNECT_SUCCEED,NET_CONNECT_DATA_EMPTY,NET_NOT_CONNECTED,NET_SERVER_CONNECTED_ERROR,NET_SERVER_ERROR,NET_SERVER_PARAM_ERROR,NET_UNKNOWN_ERROR

}